version: '3'
services:
  api:
    build: .
    ports:
      - '4000:4000'
    networks:
      - host
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tools
    networks:
      - host

networks:
  host:
    driver: bridge
